from microbit import *


while True:
    display.show(Image.HAPPY)
    sleep(1000)
    display.show(Image.HEART)
    sleep(1000)
    display.show(Image.HEART_SMALL)
    sleep(1000)
    display.show(Image.SMILE)
    sleep(1000)
    display.show(Image.SAD)
    sleep(1000)
    display.show(Image.CONFUSED)
    sleep(1000)
    display.show(Image.ANGRY)
    sleep(1000)
    display.show(Image.ASLEEP)
    sleep(1000)
    display.show(Image.SURPRISED)
    sleep(1000)
    display.show(Image.SILLY)
    sleep(1000)
    display.show(Image.FABULOUS)
    sleep(1000)
